# Generated by Django 6.0.5 on 2026-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('turma', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
