# Generated by Django 6.0.5 on 2026-05-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='synced',
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='local_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
